//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEM()
        {
            this.SEM_ACTIVIDAD = new HashSet<SEM_ACTIVIDAD>();
        }
    
        public int IdSEM { get; set; }
        public string NombreSEM { get; set; }
        public int IdUUNN { get; set; }
        public int IdResponsable { get; set; }
        public string EsPrincipal { get; set; }
    
        public virtual RESPONSABLE RESPONSABLE { get; set; }
        public virtual UUNN UUNN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEM_ACTIVIDAD> SEM_ACTIVIDAD { get; set; }
    }
}
