//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEM_ACTIVIDAD
    {
        public int IdSEMACT { get; set; }
        public int IdSEM { get; set; }
        public int IdActividad { get; set; }
        public int Periodo { get; set; }
        public int IdEstado { get; set; }
        public int IdInforme { get; set; }
        public Nullable<System.DateTime> FEjec { get; set; }
        public Nullable<int> IdRevisor { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Comunicado { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Anio { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual INFORME INFORME { get; set; }
        public virtual SEM SEM { get; set; }
    }
}
